### PR TITLE
fix(apps): unbreak Linux nightly — Linux icon walk also consumes the data-URL helpers

### PR DESCRIPTION
**Pull request by jamesbrink**
## Summary

Nightly Linux builds (both `linux-x86_64` and `linux-aarch64`) have been failing since #729 with:

```
error[E0425]: cannot find function `image_data_url_from_file` in this scope
   --> src-tauri/src/commands/apps.rs:576:16
```

#729 narrowed `data_url_from_bytes` and `image_data_url_from_file` to `#[cfg(target_os = "macos")]` on the (incorrect) claim that `mac_icon_from_app_bundle` was their only consumer. The Linux icon walk (`find_icon_file_recursive`, `app_icon_data_url`) also calls `image_data_url_from_file`, so every Linux Tauri build has failed since.

PR CI didn't catch it because `cargo clippy` only lints `claudette`, `claudette-server`, `claudette-cli` (not `claudette-tauri`, which needs system libs not installed on the lint runner). Only nightly's actual Tauri bundle build hits the missing function — which is what we saw on every nightly since `73efe0b6`.

## Fix

- Re-gate `data_url_from_bytes`, `image_data_url_from_file`, and the `base64` import they need to `#[cfg(any(target_os = "macos", target_os = "linux"))]`.
- Refresh the leading comment to list both consumers (was stale; claimed macOS-only).

## Regression coverage

Five new tests in `commands::apps::tests` pin both the cross-platform availability and the end-to-end Linux walk. They're cfg-gated so re-tightening either helper to a single platform causes the **tests** to fail to compile on the dropped platform — turning the silent build break into a loud test break:

- `data_url_from_bytes_encodes_payload` *(macOS + Linux)*
- `image_data_url_from_file_returns_data_url_for_known_extensions` *(macOS + Linux)*
- `image_data_url_from_file_rejects_unknown_extension` *(macOS + Linux)*
- `linux_find_icon_file_recursive_returns_path_consumable_by_data_url_helper` *(Linux)*
- `linux_find_icon_file_recursive_skips_non_image_extensions` *(Linux)*

The Linux end-to-end test is the one that *exactly* mirrors the call site that broke — staging an XDG-style icon tree, running `find_icon_file_recursive`, and feeding the result through `image_data_url_from_file`.

## Validation

- `cargo build -p claudette-tauri --no-default-features --features 'tauri/custom-protocol,server'` — clean.
- `cargo clippy -p claudette -p claudette-server -p claudette-cli --all-targets --all-features` — clean (CI's lint set).
- `cargo test -p claudette-tauri --no-default-features --features 'tauri/custom-protocol,server' --bins commands::apps::` — 22 tests pass on macOS (5 new; 2 of the 5 are Linux-cfg and correctly excluded here).
- `cargo fmt --all --check` — clean.

## Follow-up worth considering (out of scope)

PR CI doesn't compile or lint `claudette-tauri` on Linux at all — that's the structural gap that let #729 ship. Either adding a `cargo check -p claudette-tauri` step on a Linux runner with `libwebkit2gtk-4.1-dev` + friends installed, or a `cargo check --target aarch64-unknown-linux-gnu` pass with the system deps stubbed, would catch the next instance of this class of regression at PR time instead of nightly.

### CODE REVIEW

File: src-tauri/src/commands/apps.rs [hunk 1]
```diff
@@ -2244,4 +2246,124 @@ mod tests {
...
+    /// recursive walk or the data-URL helper is gated wrong on Linux,
+    /// this test stops compiling on Linux.
+    #[cfg(target_os = "linux")]
+    #[test]
+    fn linux_find_icon_file_recursive_returns_path_consumable_by_data_url_helper() {
+        let tmp = tempfile::tempdir().unwrap();
+        // Mimic an XDG-style tree: $root/icons/hicolor/16x16/apps/myapp.png
+        let icon_dir = tmp.path().join("icons/hicolor/16x16/apps");
+        std::fs::create_dir_all(&icon_dir).unwrap();
+        let icon_path = icon_dir.join("myapp.png");
```
[the remark this answers is not in the document]
Comment (jamesbrink) [reply src-tauri/src/commands/apps.rs:2340]: Addressed in 45c8b413 — the test now stages the icon under `tmp/icons/hicolor/16x16/apps/myapp.png` and passes `tmp.path().join("icons")` to `find_icon_file_recursive`, matching the production call where each entry of `linux_icon_roots()` (`/usr/share/icons`, `~/.local/share/icons`, …) is fed in directly.

File: src-tauri/src/commands/apps.rs [hunk 2]
```diff
@@ -2244,4 +2246,124 @@ mod tests {
...
+    /// `myapp.png` and surface a missing-icon to the UI.
+    #[cfg(target_os = "linux")]
+    #[test]
+    fn linux_find_icon_file_recursive_skips_non_image_extensions() {
+        let tmp = tempfile::tempdir().unwrap();
+        let dir = tmp.path().join("icons/hicolor/16x16/apps");
+        std::fs::create_dir_all(&dir).unwrap();
+        // Decoy first — a file with the right stem but unsupported ext.
+        std::fs::write(dir.join("myapp.txt"), b"not an icon").unwrap();
+        // Real icon at a deeper-but-valid path.
```
[the remark this answers is not in the document]
Comment (jamesbrink) [reply src-tauri/src/commands/apps.rs]: Addressed in 45c8b413 — the decoy still lives in `hicolor/16x16/apps/myapp.txt`, but the real icon now lives in `hicolor/scalable/apps/myapp.svg`. The walker has to reach past the shallow decoy to find the real file, so the "deeper-but-valid path" wording matches what the fixture actually does.
